<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_This order contains a gift_proceedToR_057b5e</name>
   <tag></tag>
   <elementGuidId>188bed2c-eca9-49e3-b56c-f16640be9d38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='proceedToRetailCheckout']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;proceedToRetailCheckout&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Proceed to Buy\n                    \n                    \n                \n                \n                    Buy Amazon items&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>372aaa61-3b24-4eb9-820a-7ba493a2b831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>proceedToRetailCheckout</value>
      <webElementGuid>15b51ed4-9a95-4445-bbdb-157c712a6bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-feature-id</name>
      <type>Main</type>
      <value>proceed-to-checkout-action</value>
      <webElementGuid>05f22f8a-13ec-449f-84eb-64f56c34805e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a-button-input</value>
      <webElementGuid>1ac8c2f2-f656-49e0-9579-d34c3e35eeba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9b1e0bb6-0dd3-4a48-90f3-9d78d2db0869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Proceed to checkout</value>
      <webElementGuid>60b1ba41-d6ec-4e76-b6bd-1868434469db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>sc-buy-box-ptc-button-announce</value>
      <webElementGuid>4f7e8a8a-4b63-427c-8f28-acdfc4050ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sc-buy-box-ptc-button&quot;)/span[@class=&quot;a-button-inner&quot;]/input[@class=&quot;a-button-input&quot;]</value>
      <webElementGuid>a1769a39-da3e-45ee-821e-7a1523f1799c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='proceedToRetailCheckout']</value>
      <webElementGuid>5459dbdd-6e8a-48fc-a56b-094f27aa72e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='sc-buy-box-ptc-button']/span/input</value>
      <webElementGuid>67f49e49-f943-41f3-a5cd-40f6f90720b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/input</value>
      <webElementGuid>2872c41e-3002-4238-841b-62bafb785ea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'proceedToRetailCheckout' and @type = 'submit']</value>
      <webElementGuid>c8111cf9-f637-4cb2-a690-a9ab239279eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
